name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/**'
      - '!.github/scripts/generate_wiki.py'
      - 'README.md'
  pull_request:
  workflow_dispatch:

jobs:
  UpdateWiki:
    name: Update wiki results pages
    runs-on: ubuntu-latest
    steps:
    - name: Clone tree
      uses: actions/checkout@v4
      with:
        submodules: recursive
        path: results
    - name: Clone wiki
      uses: actions/checkout@v4
      with:
        repository: ${{github.repository}}.wiki
        path: wiki
    - name: Generate wiki content
      run: |
        ./results/.github/scripts/generate_wiki.py results/results wiki -v
    - name: Commit changes
      if: github.event_name == 'workflow_dispatch' || (github.ref == 'refs/heads/main' && github.event_name == 'push')
      run: |
        cd wiki
        find .
        git config --local user.email "$GITHUB_ACTOR+github-actions@users.noreply.github.com"
        git config --local user.name "$GITHUB_ACTOR via action"
        git add .
        git diff-index --quiet HEAD || git commit -m "Update from github action $GITHUB_RUN_NUMBER - $GITHUB_SHA"
        git push
